### ISSUE TITLE
Create Task Backend - This will send user task information to the database so it can be retrieved later on

### ISSUE THREAD

**Issue by raquelgrogan** [COSC481W-2021Fall/capstone-runtime-terror#23]
# Task

* Retrieve task information from the database

* Send the retrieved information to the front end

* Send an error message to the front end if something goes wrong

# Acceptance Criteria
- [ ] Be able to update data and send to database

- [ ] Be able to send newly created task to database

- [ ] Add error checking and send to front end to alert user of error
