### ISSUE TITLE
Dashboard Backend - This will fetch the tasks' information from the database and send it to the front end to be displayed to the user

### ISSUE THREAD

**Issue by Abdul-Hai1** [COSC481W-2021Fall/capstone-runtime-terror#25]
# Task List
* Retrieve task information from the database

* Send the retrieved information to the front end

* Send an error message to the front end if something goes wrong

# Acceptance Criteria
- [ ] Retrieves information from database

- [ ] Sends information to the front end

- [ ] Sends an error message to the front end if something goes wrong
